name: .NET

on: [push, pull_request]

jobs:
  build_and_tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore Backend/FoodCounter.Api/
    - name: Api_Build
      run: dotnet build Backend/FoodCounter.Api/ --no-restore
    - name: Api_UnitTest
      run: dotnet test Backend/FoodCounter.Api/ --no-build --verbosity normal
    - name: Api_Run
      run: dotnet run --project Backend/FoodCounter.Api/FoodCounter.Api/FoodCounter.Api.csproj --no-build --verbosity normal &
    - name: Api_PostmanTests
      run: docker run --net=host -v $(pwd)/Backend/Postman:/etc/newman -t postman/newman:latest run "FoodCounter.postman_collection.json" --reporters="cli"