name: .NET

on: [push, pull_request]

jobs:
  build_and_tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore Backend/FoodCounter.Api/
    - name: Build
      run: dotnet build Backend/FoodCounter.Api/ --no-restore
    - name: Test
      run: dotnet test Backend/FoodCounter.Api/ --no-build --verbosity normal
    - name: RunApi
      run: dotnet run --project Backend/FoodCounter.Api/FoodCounter.Api/FoodCounter.Api.csproj --no-build --verbosity normal &
    - name: Post
      run: ls && ls Backend && ls Backend/Postman
      #run: docker run -v $(pwd)/test:/etc/newman -t postman/newman:latest run "Backend/Postman/FoodCounter.postman_collection.json" --reporters="cli"
      

    #   run: sleep 10 && curl http://localhost:5000/aliments/4
    # - name: Test
    #   run: dotnet test Backend/FoodCounter.Api/ --no-build --verbosity normal
    # - name: CountCodeLines
    #   run: find Backend/FoodCounter.Api -name '*.cs' | xargs wc -l
