name: .NET

on: [push, pull_request]

jobs:
  build_and_tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore Backend/FoodCounter.Api/

    - name: Get Oauth2 Google
      run: curl https://accounts.google.com/o/oauth2/token   -d code=${{ secrets.GOOGLE_CODE }}   -d client_id=${{ secrets.GOOGLE_CLIENT_ID }} -d client_secret=${{ secrets.GOOGLE_CLIENT_SECRET }} -d redirect_uri=${{ secrets.GOOGLE_REDIRECT }} -d access_type=offline -d grant_type=authorization_code

